In [2]:
import numpy as np
import pandas as pd


In [3]:
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
print(temperatures_w1)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [4]:
print("Shape:", temperatures_w1.shape)
print("Data Type:", temperatures_w1.dtype)
print("Number of Elements:", temperatures_w1.size)

Shape: (7,)
Data Type: float64
Number of Elements: 7


In [5]:
#converting celcious to fahhrenheit

In [6]:
fahrenheit = (temperatures_w1 * 9/5) + 32
print("Fahrenheit:", fahrenheit)

Fahrenheit: [72.5  77.54 69.44 74.12 78.98 76.64 71.42]


In [7]:
print("Max Temp:", np.max(temperatures_w1))
print("Min Temp:", np.min(temperatures_w1))
print("Mean Temp:", np.mean(temperatures_w1))

Max Temp: 26.1
Min Temp: 20.8
Mean Temp: 23.542857142857144


In [8]:
# First three days
print("First 3 Days:", temperatures_w1[:3])



First 3 Days: [22.5 25.3 20.8]


In [9]:


# Weekend (last 2 days)
print("Weekend:", temperatures_w1[-2:])

# Middledays
print("Middle 3 Days:", temperatures_w1[2:5])

Weekend: [24.8 21.9]
Middle 3 Days: [20.8 23.4 26.1]


In [11]:
#2d array
temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]
])
print(temperatures)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


In [12]:
print("Shape:", temperatures.shape)
print("Data Type:", temperatures.dtype)
print("Total Elements:", temperatures.size)

# Each week
print("Week 1:", temperatures[0])
print("Week 2:", temperatures[1])

# Weekend (last 2 days of both weeks)
print("Weekend both weeks:\n", temperatures[:, -2:])

Shape: (2, 7)
Data Type: float64
Total Elements: 14
Week 1: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Week 2: [19.2 22.5 21.3 24.  23.5 22.8 20.1]
Weekend both weeks:
 [[24.8 21.9]
 [22.8 20.1]]


In [13]:
#pandas

In [14]:
marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)
print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


In [15]:
# 1st rank using position
print("1st Rank:", marks.iloc[0])

# Top 3 using loc
print("Top 3:\n", marks.loc[['Rank1', 'Rank2', 'Rank3']])

# 3rd rank using iloc
print("3rd Rank:", marks.iloc[2])

# Boolean mask (>90)
print("Marks > 90:\n", marks[marks > 90])

1st Rank: 95
Top 3:
 Rank1    95
Rank2    92
Rank3    89
dtype: int64
3rd Rank: 89
Marks > 90:
 Rank1    95
Rank2    92
dtype: int64


In [16]:
# Modifying Rank1
marks['Rank1'] = 100

# Remove last rank
marks = marks.drop('Rank5')

# Compute CGPA
cgpa = marks / 10

print("Updated Marks:\n", marks)
print("CGPA:\n", cgpa)

Updated Marks:
 Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64
CGPA:
 Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


In [17]:
#data frame

In [18]:
transactions = pd.DataFrame({
    'TransactionID': [101,102,103,104,105,106,107,108,109,110],
    'ProductCategory': ['Electronics','Clothing','Electronics','Furniture','Clothing',
                        'Electronics','Furniture','Clothing','Furniture','Electronics'],
    'Region': ['North','South','North','East','West','North','East','West','South','North'],
    'Amount': [200,150,300,450,200,250,300,180,350,400]
})

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [19]:
# Head, Tail
print(transactions.head())
print(transactions.tail())

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [20]:
# Shape
print("Shape:", transactions.shape)

# Columns
print("Columns:", transactions.columns)

Shape: (10, 4)
Columns: Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')


In [21]:
# Data types
print(transactions.dtypes)

TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object


In [22]:
# Select columns
print(transactions[['ProductCategory', 'Amount']])


  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400


In [23]:
# Last 3 columns
print(transactions.iloc[:, -3:])

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400


In [24]:
# Filter condition
filtered = transactions[(transactions['Region'] == 'North') & (transactions['Amount'] > 200)]
print(filtered)

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400


In [25]:
# Value counts
print(transactions['ProductCategory'].value_counts())

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64


In [26]:
# Unique regions
print(transactions['Region'].unique())

['North' 'South' 'East' 'West']


In [27]:
# Group by Region
print(transactions.groupby('Region')['Amount'].mean())

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64


In [28]:
transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165

In [29]:
#add discount
transactions['Discount'] = transactions['Amount'] * 0.10


In [30]:
#remove 109
transactions = transactions[transactions['TransactionID'] != 109]

In [31]:
#del discounrt
transactions = transactions.drop(columns=['Discount'])

In [32]:
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400
